const express = require('express');
const cors = require('cors');
const dotenv = require('dotenv');
const mongoose = require('mongoose');
const { trainModel, getResponse } = require('./nlp');
const { syncData } = require('./services/syncService');
const Knowledge = require('./models/Knowledge');
const Message = require('./models/Message');
const { startHeartbeat } = require('./utils/heartbeat');

dotenv.config();

const app = express();
app.use(cors());
app.use(express.json());

let mainConn;

// ─── API Endpoints ─────────────────────────────────────────────────────────

// Chat UI Endpoint
app.post('/api/chat', async (req, res) => {
  try {
    const { message } = req.body;
    if (!message) return res.status(400).json({ error: 'Message is required' });

    const result = await getResponse(message);
    
    // -- LIVE Dynamic DB Connection --
    if (result.intent === 'hkca.events.list' && mainConn) {
       const liveEvents = await mainConn.collection('events').find({ status: 'published' }).project({ title: 1 }).toArray();
       
       if (liveEvents.length > 0) {
           result.options = liveEvents.map(e => ({
               label: e.title,
               query: `Tell me about ${e.title}` // This perfectly matches the utterance generated by syncService.js
           }));
       } else {
           result.answer = 'Currently, there are no upcoming events listed. Please check back later!';
       }
    }

    // Log message history
    await Message.create({
      userMessage: message,
      botResponse: result.answer,
      intent: result.intent,
      score: result.score
    });

    res.json(result);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

// Manual Sync & Re-train
app.post('/api/sync', async (req, res) => {
  try {
    await syncData(mainConn);
    await trainModel();
    res.json({ message: 'Sync and Re-training completed' });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

// Admin CRUD: List Knowledge
app.get('/api/knowledge', async (req, res) => {
  try {
    const data = await Knowledge.find().sort({ createdAt: -1 });
    res.json(data);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

// Admin CRUD: Add/Update Knowledge
app.post('/api/knowledge', async (req, res) => {
  try {
    const { intent, category, utterances, answers } = req.body;
    const record = await Knowledge.findOneAndUpdate(
      { intent },
      { category, utterances, answers },
      { upsert: true, new: true }
    );
    res.json(record);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

// Admin CRUD: Delete Knowledge
app.delete('/api/knowledge/:id', async (req, res) => {
  try {
    await Knowledge.findByIdAndDelete(req.params.id);
    res.json({ message: 'Entry deleted successfully' });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

// Admin View: History
app.get('/api/history', async (req, res) => {
  try {
    const messages = await Message.find().sort({ createdAt: -1 }).limit(100);
    res.json(messages);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

// Heartbeat Endpoint
app.get('/api/health', (req, res) => {
  res.status(200).json({ status: 'ok' });
});

// ─── Server Bootstrap ─────────────────────────────────────────────────────

const startServer = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI_CHATBOT);
    console.log('Chatbot Primary DB Connected');

    mainConn = await mongoose.createConnection(process.env.MONGO_URI_MAIN).asPromise();
    console.log('Main HKCA DB Connected for Sync');

    await syncData(mainConn);
    await trainModel();
    startHeartbeat();

    const PORT = process.env.PORT || 5005;
    app.listen(PORT, () => {
      console.log(`Chatbot Server running on port ${PORT}`);
    });
  } catch (error) {
    console.error('Server Start Error:', error);
  }
};

startServer();
